name: LeeesAntiBot
version: 3.0.0
main: Main
api-version: 1.16
authors: [Nate, Legault]
description: Chat whitelist plugin for anarchy servers
website: http://6b6t.org
commands:
  blacklist:
    permission: whitelist.admin
  whitelist:
    permission: whitelist.admin
