name: LeeesAntiBot
version: 3.0.0
main: Leees.Chat.Whitelist.Main
api-version: 1.13
authors: [Nate, Legault]
description: Chat whitelist plugin for anarchy servers
website: http://6b6t.org
commands:
  blacklist:
    permission: whitelist.admin
  whitelist:
    permission: whitelist.admin
